---
title: "Hotel-Review"
author: "Saluna Alavi/123190049-Fatkur Rizal Rochmadian Putra/123190130-Bayu Fitri Pamungkas/123190076"
date: "12/4/2021"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(shiny)
library(here)
library(vroom)
library(tm)
library(RTextTools)
library(dplyr)
library(ggplot2)
library(plotly)
library(syuzhet)
library(e1071)
library(caret)
library(wordcloud)
```
```{r}
hotel <- vroom(here("Datafiniti_Hotel_Reviews_Jun19.csv"))
komen <- hotel$reviews.title
komen_c <- Corpus(VectorSource(komen))
removeURL <- function(x) gsub("http[^[:space:]]*", "", x)
reviewclean <- tm_map(komen_c, removeURL)
removeNL <- function(y) gsub("\n", " ", y)
reviewclean <- tm_map(reviewclean, removeNL)
replacecomma <- function(y) gsub(",", "", y)
reviewclean <- tm_map(reviewclean, replacecomma)
removetitik2 <- function(y) gsub(":", "", y)
reviewclean <- tm_map(reviewclean, removetitik2)
removetitikkoma <- function(y) gsub(";", " ", y)
reviewclean <- tm_map(reviewclean, removetitikkoma)
removetitik3 <- function(y) gsub("p…", "", y)
reviewclean <- tm_map(reviewclean, removetitik3)
removeamp <- function(y) gsub("&amp;", "", y)
reviewclean <- tm_map(reviewclean, removeamp)
removeUN <- function(z) gsub("@\\w+", "", z)
reviewclean <- tm_map(reviewclean, removeUN)
remove.all <- function(xy) gsub("[^[:alpha:][:space:]]*", "", xy)
reviewclean <- tm_map(reviewclean,remove.all)
reviewclean <- tm_map(reviewclean, removePunctuation)
reviewclean <- tm_map(reviewclean, tolower)
myStopwords = readLines("stopwords-en.txt")
reviewclean <- tm_map(reviewclean,removeWords,myStopwords)

dataframe <- data.frame(text = unlist(sapply(reviewclean, '[')), stringsAsFactors = F)
View(dataframe)
write.csv(dataframe, file = 'reviewclean.csv')
```
```{r}
data_bersih <- read.csv("reviewclean.csv", stringsAsFactors = F)
review <- as.character(data_bersih$text)
get_nrc_sentiment('happy')
get_nrc_sentiment('excitement')
review_nrc <- get_nrc_sentiment(review)

review_bind <- cbind(data_bersih$text, review_nrc)
par(mar = rep(3, 4))
barplot1 <- barplot(colSums(review_nrc), col = rainbow(10), ylab = 'count', main = 'Sentiment Analisis')
barplot2 <- barplot1
```
```{r}
df <- read.csv("reviewclean.csv", stringsAsFactors = F)
glimpse(df)

set.seed(20)
df <- df[sample(nrow(df)),]
df <- df[sample(nrow(df)),]
glimpse(df)

corpus_me <- Corpus(VectorSource(df$text))
corpus_me
inspect(corpus_me[1:10])

corpus_clean <- corpus_me %>%
  tm_map(content_transformer(tolower)) %>%
  tm_map(removePunctuation) %>%
  tm_map(removeNumbers) %>%
  tm_map(removeWords, stopwords(kind = "en")) %>%
  tm_map(stripWhitespace)
dtm <- DocumentTermMatrix(corpus_clean)

inspect(dtm[1:10, 1:20])

df_train <- df[1:100,]
df_test <- df[101:200,]
dtm_train <- dtm[1:100,]
dtm_test <- dtm[101:200,]

corpus_clean_train <- corpus_clean[1:100]
corpus_clean_test <- corpus_clean[101:200]

dim(dtm_train)
fivefreq <- findFreqTerms(dtm_train, 5)
length(fivefreq)

dtm_train_nb <- DocumentTermMatrix(corpus_clean_train, control = list(dictionary = fivefreq))

dtm_test_nb <- DocumentTermMatrix(corpus_clean_test, control = list(dictionary = fivefreq))

dim(dtm_test_nb)

convert_count <- function(x){
  y <- ifelse(x > 0, 1, 0)
  y <- factor(y, levels = c(0, 1), labels = c("no", "yes"))
  y
}
trainNB <- apply(dtm_train_nb, 2, convert_count)
testNB <- apply(dtm_test_nb, 1, convert_count)

wordcloud(corpus_clean, min.freq = 4, max.words = 50, random.order = F, colors = brewer.pal(8, "Dark2"))
```
```{r}
server <- function(input, output) {
  output$tbl = DT::renderDataTable({
    DT::datatable(hotel, options = list(lengthChange = F))
  })
  
  output$scatterplot <- renderPlot({
    review_dataset <- read.csv("reviewclean.csv", stringsAsFactors = F)
    
    review_ds <- as.character(review_dataset$text)
    
    get_nrc_sentiment('happy')
    get_nrc_sentiment('excitement')
    s <- get_nrc_sentiment(review_ds)
    
    review_combine <- cbind(review_dataset$text, s)
    par(mar = rep(3, 4))
    barplot(colSums(s), col = rainbow(10), ylab = 'count', main = 'Sentiment Analisis')
  }, height = 400)
  
  output$wordcloud <- renderPlot({
    df <- read.csv("reviewclean.csv", stringsAsFactors = F)
    set.seed(20)
    df <- df[sample(nrow(df)),]
    df <- df[sample(nrow(df)),]
    glimpse(df)
    
    corpus_me <- Corpus(VectorSource(df$text))
    corpus_me
    inspect(corpus_me[1:10])
    
    corpus_clean <- corpus_me %>%
      tm_map(content_transformer(tolower)) %>%
      tm_map(removePunctuation) %>%
      tm_map(removeNumbers) %>%
      tm_map(removeWords, stopwords(kind = "en")) %>%
      tm_map(stripWhitespace)
    dtm <- DocumentTermMatrix(corpus_clean)
    
    inspect(dtm[1:10, 1:20])
    
    df_train <- df[1:100,]
    df_test <- df[101:200,]
    dtm_train <- dtm[1:100,]
    dtm_test <- dtm[101:200,]
    
    corpus_clean_train <- corpus_clean[1:100]
    corpus_clean_test <- corpus_clean[101:200]
    
    dim(dtm_train)
    fivefreq <- findFreqTerms(dtm_train, 5)
    length(fivefreq)
    
    dtm_train_nb <- DocumentTermMatrix(corpus_clean_train, control = list(dictionary = fivefreq))
    
    dtm_test_nb <- DocumentTermMatrix(corpus_clean_test, control = list(dictionary = fivefreq))
    
    dim(dtm_test_nb)
    
    convert_count <- function(x){
      y <- ifelse(x > 0, 1, 0)
      y <- factor(y, levels = c(0, 1), labels = c("no", "yes"))
      y
    }
    trainNB <- apply(dtm_train_nb, 2, convert_count)
    testNB <- apply(dtm_test_nb, 1, convert_count)
    
    wordcloud(corpus_clean, min.freq = 4, max.words = 50, random.order = F, colors = brewer.pal(8, "Dark2"))
  })
}
```
```{r}
hotel <- vroom(here("reviewclean.csv"))
a <- hotel$text
ui <- fluidPage(
  titlePanel("Data Review Hotel"),
  mainPanel(
    tabsetPanel(type = "tabs",
                tabPanel("Dataset Review Hotel", DT::dataTableOutput('tbl')),
                tabPanel("Scatterplot", plotOutput("scatterplot")),
                tabPanel("Wordcloud", plotOutput("wordcloud"))
          )
      )
  )

```
```{r}
shinyApp(ui = ui, server = server)
```



